# *** Nginx configuration for laserCam ***

# HTTP to HTTPS redirect
server {
    listen 80;
    server_name _;

    allow 192.168.1.0/24;    # Local network
    allow 172.16.0.0/12;     # Zerotier network
    allow 127.0.0.1;         # Localhost
    deny all;

    return 301 https://$host$request_uri;
    #location / {
    #    proxy_pass http://127.0.0.1:5000;
    #    proxy_set_header Host $host;
    #}
}

# HTTPS server
server {
    listen 443 ssl;
    server_name _;

    # SSL certificate and key
    ssl_certificate /etc/ssl/certs/laserCam.crt;
    ssl_certificate_key /etc/ssl/private/laserCam.key;

    # SSL security settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    allow 192.168.1.0/24;    # Local network
    allow 172.16.0.0/12;     # Zerotier network
    allow 127.0.0.1;         # Localhost
    deny all;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /socket.io/ {
        proxy_pass http://127.0.0.1:5000/socket.io/;
        proxy_http_version 1.1; # Required for WebSockets

        # Magic headers that transform the connection from HTTP into a persistent WebSocket stream
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Disable buffering to avoid joystick lag spikes
        proxy_buffering off;
    }

    location /stream/ {
        # This routes all traffic for the player and the stream to MediaMTX
        proxy_pass http://127.0.0.1:8889/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
